### ISSUE TITLE
No Response in iOS 11 after short time

### ISSUE THREAD

**Issue by smarl** [chanomie/homebridge-connectedbytcp#5]
I now see No Response on all icons after upgrading to iOS 11. It works for a little while after I restart the node process, but then it gives up.

**Comment by chanomie** [comment]
It's been working fine for me - but anything in the Homebridge console?  It should be showing logs each time it tries to update.

Is your light switch on (bulbs getting power) when this happens?

**Comment by smarl** [comment]
After a reinstall, everything seems okay again.
